name:                     "Crowdsourcing"
sub-name:                 "for the Humanities"
# is this a lab site or project site?
type:                      project
markdown:                 redcarpet
highlighter:              pygments
description:              "A research project at the Center for Spatial and Textual Analysis (CESTA), Stanford University."
category_dir :
category_title_prefix :   ''
category_title :          ''
google_id:                ''
disqus:                   ''
url:                      http://humanitiescrowdsourcing.stanford.edu/
permalink:                /:year/:month/:day/:title/
twitter:
banner-img-url:           "https://googledrive.com/host/0B9__iE30PYDoR0RVbmxvbVpjSjQ/"

links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Tools
    url: /tools/
  - title: People
    url: /people/

projects:
  - title: Living with the Railroads
    url: living-with-railroads
  - title: Year of the Bay
    url: year-of-the-bay
  - title: Emotions of London
    url: emotions-of-london
